# Exercise: NumPy Arrays

1) Create an arbitrary one dimensional array called "v".

In [3]:
import numpy as np

In [4]:
v = np.array([1,2,3,4,5,5])
v

array([1, 2, 3, 4, 5, 5])

2) Create a new array which consists of the odd indices of previously created array "v".

In [5]:
odd_v = v[::2]

In [6]:
y = v[::2]
y

array([1, 3, 5])

3) Create a new array in backwards ordering from v.

In [7]:
rev_v = v[::-1]

In [8]:
rev_v

array([5, 5, 4, 3, 2, 1])

In [9]:
rev_v2 = reversed(v)
rev_v2

In [10]:
list(rev_v2)

[5, 5, 4, 3, 2, 1]

4) What will be the output of the following code:

       a = np.array([1, 2, 3, 4, 5])
       b = a[1:4]
       b[0] = 200
       print(a[1])

In [11]:
a = np.array([1, 2, 3, 4, 5])
b = a[1:4]
b[0] = 200
print(a[1])

200


5) Create a two dimensional array called "m".

In [16]:
m= np.array([[1,2,3,4,5], [6,7,8,9,0],[11,12,13,14,15]])
print(m)

[[ 1  2  3  4  5]
 [ 6  7  8  9  0]
 [11 12 13 14 15]]




6) Create a new array from m, in which the elements of each row are in reverse order.

In [14]:
new_m = m[:: , ::-1]

In [15]:
new_m

array([[ 5,  4,  3,  2,  1],
       [ 0,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

7) Another one, where the rows are in reverse order.

In [27]:
new_m1 = m[::-1]
new_m1

array([[6, 7, 8, 9, 0],
       [1, 2, 3, 4, 5]])

8) Create an array from m, where columns and rows are in reverse order.

In [35]:
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9,  0],
       [11, 12, 13, 14, 15]])

In [36]:
rev_m = m[::-1 , ::-1]

In [37]:
rev_m

array([[15, 14, 13, 12, 11],
       [ 0,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

9) Cut of the first and last row and the first and last column.

In [38]:
new_m3 = m[1:-1, 1:-1]
new_m3

array([[7, 8, 9]])

In [17]:
len([[2,3,1,0], [2,3,1,0], [3,2,1,1]])

3