In [1]:
import numpy as np

In [2]:
#generate some random numbers (2 rows and 3 columns)
data = np.random.rand(2,3)

In [3]:
data

array([[0.81486374, 0.59731407, 0.44665974],
       [0.37134547, 0.64555788, 0.92892896]])

In [4]:
data * 10

array([[8.14863741, 5.97314068, 4.46659742],
       [3.71345467, 6.45557883, 9.28928955]])

In [5]:
# divide every value by 2
data / 2

array([[0.40743187, 0.29865703, 0.22332987],
       [0.18567273, 0.32277894, 0.46446448]])

In [6]:
data + data

array([[1.62972748, 1.19462814, 0.89331948],
       [0.74269093, 1.29111577, 1.85785791]])

In [7]:
data.dtype

dtype('float64')

In [12]:
# define a list of values
mylist = [6,7.5,5,8,0,1]

In [13]:
arr1 = np.array(mylist)
arr1

array([6. , 7.5, 5. , 8. , 0. , 1. ])

In [14]:
arr1.dtype

dtype('float64')

In [15]:
data2 = [[1,2,3], [5,6,7,8]]

In [17]:
arr2 = np.array(data2)
arr2

array([list([1, 2, 3]), list([5, 6, 7, 8])], dtype=object)

In [18]:
arr2.dtype

dtype('O')

In [20]:
zeroes = np.zeros(10)
zeroes

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
zeroes = np.zeros((3,6))
zeroes

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]